COMPLIMENTS = [
    "Tanta curva y yo sin frenos",
    "Dios se pasó al crearte a ti.",
    "Se están cayendo ángeles del cielo",
    "Mi Sol, mi vida y mi todo eres Tú…",
    "Qué Dios te guarde y me dé la llave!",
    "¿Te dolió caer del cielo… angelito?",
    "Si no existieras… te inventaría!!!",
    "¡Estás hecha con lo mejor del planeta!",
    "¿Qué estudias? -Desde hoy… tus ojos",
    "No soy yo, son mis ganas de tenerte…",
    "¿Tus padres han estudiado Bellas Artes?",
    "Al ver a una hermosa vestida de negro:",
    "Cuando me miras puedo ver cosas divinas",
    "Quién fuera piso para sentir tu caminar",
    "¡Quién fuera bizco para verte dos veces!",
    "Lindas palabras para enamorar a una mujer",
    "Me gustaría ser voluntario de tu cuerpo.",
    "Quién fuera piso para sentir tu caminar.",
    "¿De qué juguetería te escapaste?, ¡muñeca!",
    "11 de cada 10 veces que te pienso, sonrío.",
    "Por locuras como tú, hay locos como yo..!!",
    "Quien fuera zapatero para curtir tu cuero",
    "¿Qué hace una estrella volando tan bajito?",
    "Ojala fueras una deuda, así podía levantarte",
    "La luna controla las mareas, y vos mi corazón",
    "Mátame si no te sirvo, pero pruébame primero.",
    "No soy Cupido, pero quiero flechar tu corazón.",
    "Pedí un deseo, apareciste tú, así de simple…",
    "Señora, vaya con Dios que yo voy con su hija.",
    "Te quiero más que ayer, pero menos que mañana.",
    "¡Dime cómo te llamas y te pido para los Reyes!.",
    "Como avanza la ciencia si ya las flores caminan",
    "Contigo… hasta lo imposible es fácil para mí.",
    "Me gustaría ser palabra, para estar en tu boca.",
    "Me gustaría ser papel para envolver ese bombón.",
    "Si así es el infierno, ¡que me lleve el diablo!",
    "Dos personas un camino…dos corazones un destino…",
    "Se te cayó un papel… el que te envuelve, bombón.",
    "Si fueras una aceituna me comería hasta el hueso",
    "Si parpadeo me pierdo un instante de tu belleza.",
    "Eres el te quiero aquí conmigo de todos mis días.",
    "Estás más completa que la Enciclopedia Británica.",
    "Si el sol pudiera mirarte, nunca sería de noche.",
    "Es una locura amar, a menos que se ame con locura.",
    "Eres ese mensaje que siempre me saca una sonrisa…",
    "Me gustaría ser aviador para volar en tus sueños !",
    "No me busques, prefiero seguir perdido en tu mirada",
    "Si la belleza matara, tú no tendrías perdón de Dios",
    "Como me gustaría ser visco……para mirarte doble!",
    "Me gustaría ser papa frita para acompañar ese lomo.",
    "No temas estar desnuda porque yo te vestiré de amor.",
    "Si cocinas como caminas, me como hasta la rasita!!!",
    "Te quiero tanto que el corazón se me queda estrecho.",
    "Mensajes para admirar, galantear y piropear una mujer",
    "Te conozco de memoria, porque no sales de mi mente…",
    "Creí nacer para quererte y ahora vivo para olvidarte.",
    "Eres lo único que le falta a mi vida para ser perfecto",
    "Mi vida te necesito, como al oxígeno para poder vivir.",
    "Si la belleza fuera un instante tu serías la eternidad",
    "Tu papá debe ser un pirata, porque tú eres un tesoro!",
    "No sé hacia dónde vamos, sólo sé que quiero ir contigo…",
    "Pan es pan, jalea es jalea, no hay amor sin una *pelea*",
    "Quién fuera agua para rozar tu cuerpo cuando te duches.",
    "Si amarte fuera pecado, tendría el infierno asegurado.",
    "Si fueras una lágrima no lloraría por miedo a perderte.",
    "¡Ya no puedo ni mirarte pues deslumbras más que el sol!",
    "Cuanto más te doy, Más tengo, pues ambos son infinitos.",
    "Eres como el café: dulce, caliente y me quitas el sueño.",
    "Ni mil poetas en mil años podrían describir tu belleza.",
    "Si el amor es una tontería, ¡¡¡¡Que vivan los tontos!!!!",
    "Si fuera juez, te condenaría a cadena perpetua… conmigo.",
    "Si la belleza fuera pecado tú no tendrías perdón de DIOS",
    "Amor, si amarte fuera trabajo, no existiría el desempleo.",
    "Eres como el café: dulce, caliente y me quitas el sueño.",
    "No quiero dinero ni riqueza, a mi me basta con tu belleza",
    "Si la belleza fuera dolor, mi vida, vivirías en un grito.",
    "Tus ojos son las luces que necesito en una noche oscura.",
    "¿Quién asaltó la panadería que hay tanto bizcocho suelto?",
    "Si mirases seguido al cielo, terminaría por salirte alas",
    "Tú eres la canción que canto con cada fibra de mi corazón.",
    "¡Hasta las rosas cuando te ven pasar, sienten envidia de ti!",
    "Por ti, subiría al cielo en bicicleta y bajaría sin frenos.",
    "Que Dios te guarde mi nena, y que las llaves me las de a mi",
    "Si cierro los ojos y vuelvo a abrirlos, vas a estar todavía?",
    "Tu voz se convierte en melodías que apacientan mi espíritu.",
    "De ti me gustan hasta esas cosas que no soporto en los demás.",
    "Eres el icono de la belleza, sin duda haría doble clic en ti.",
    "Me miro en el espejo y hasta mi imagen está pensando en ti…",
    "Quisiera ser gato para qué? para pasar las 7 vidas con vos!",
    "Quisiera ser un marinero para navegar por el mar de tus ojos.",
    "Señor que pasa en el cielo que los ángeles están en la tierra",
    "Si tu belleza fuera enfermedad, vida mía, no habría remedio.",
    "Ahora que te conozco, no tengo nada mas que pedirle a la vida!",
    "Quisiera nadar en tus ojos azules/negros, etc.. hasta ahogarme",
    "Si quieres saber lo que es un beso, te doy clases particulares",
    "Aquí tienes esta llave, cuando quieras puedes abrir mi corazón!",
    "Bienaventurados los borrachos, porque ellos te verán dos veces.",
    "Eres como un capuchino: dulce, caliente y me pones nervioso…",
    "Puede que no seas perfecta, pero tus defectos son encantadores.",
    "Si fuera esclavo de tu amor, viviría en la prisión del paraíso.",
    "Si que está avanzada la ciencia; que hasta los bombones caminan",
    "Eso no son dos ojos, son dos faros que han eclipsado mi corazón.",
    "Los angelitos se han enfadado conmigo porque ahora sueño contigo",
    "Quien fuera eterno mujer divina para poder amarte toda la vida.",
    "Te quiero tanto que el corazón se me hace pequeño para guardarte",
    "!Con esos ojos, quién no quisiera ser luna para cuidar tu sueño!",
    "Eres la única persona a la que cuando veo, se me olvida el mundo.",
    "Quien fuera eterno, mujer divina, para poder amarte toda la vida.",
    "Quisiera embriagarme de tu cuerpo, sin haber bebido ningún licor.",
    "Si cocinas como estás caminado, te juro de la casa hoy no salgo .",
    "Si fuera Colón, Navegaría día y noche hasta llegar a tu corazón",
    "Si la belleza fuera un delito, te hubiesen dado cadena perpetua.",
    "Viendo sonrisas así de bonitas es fácil tener un buen día, guapa!",
    "Las curvas de tu cuerpo son perfectas para el camino de mis besos.",
    "Me gustaría ser casetera para tocarte de lado a lado",
    "Puede que no seas perfecto/a, pero tus defectos son encantadores.",
    "Tú debes ser atea, porque estás como quieres y no como Dios manda.",
    "Como se habrán querido tus padres… por haberte hecho tan bonita.",
    "Eres un caudal de hermosura, tomado de la inmensidad del universo",
    "Si cocinas como estás caminado, te juro de la casa hoy no salgo …",
    "Te quiero hasta el cielo, ida y vuelta, siete veces y en triciclo.",
    "Tengo que cumplir arresto domiciliario. Puedo cumplirlo en tu casa?",
    "tu papá es pirata? – la mujer pregunta : por qué? – por el tesoro!",
    "Me gustaría que me encerraran en tu corazón y que botaran la llave.",
    "Por qué el cielo está nublado? Porque todo el azul está en tus ojos",
    "Solo con mirarte sé que nunca voy a sentir lo mismo por alguien más.",
    "Cualquiera persona sana que te conozca puede volverse loco por ti..!!",
    "La vida se viste de rosa, pues vivir contigo no es cualquier cosa!…",
    "Nunca me ha gustado estar cerca de algo que está lejos de tu alcance.",
    "Quién se murió en el cielo, que hasta los angelitos andan de negro…",
    "Si quieres encontrar a tu príncipe azul, tendrás que besar a este sapo",
    "Si tuviera un dólar por cada beso, que me das, sería un rico enamorado",
    "Nunca me ha gustado estar cerca de algo que estas lejos de mi alcance.",
    "Sabes porque el mar es salado? Porque tú te llevaste toda su dulzura…",
    "Si el propósito de la vida es el amor, entonces mi propósito eres tú…",
    "Si quieres encontrar a tu príncipe azul, tendrás que besar a este sapo.",
    "Como tú ninguna, para hacer otra como tú, hay que hacerla a la medida…",
    "Piropos de amor para halagar y galantear una mujer hermosa y encantadora",
    "Quisiera nacer de nuevo para no perderme ni uno solo de tus amaneceres.",
    "Si Adán por Eva se comió una manzana, yo por Ti me comería una frutería.",
    "Si fueras el diablo!, como me gustaría estar en el infierno Preciosa!!!",
    "No se cómo lo nuestro empezó, pero sí sé que NO QUIERO que termine nunca.",
    "Mi Dios debe estar bien distraído, ya los angelitos se le están escapando.",
    "Pasa una mujer y dice adiós… -a DIOS lo vi cuando me miraron tus ojos !!",
    "Por ti mamacita, subiría en bicicleta hasta el cielo y bajaría sin frenos.",
    "Te deseo de todo corazón lo mejor y lo mejor que te puede pasar… soy yo.",
    "Tienes todo lo que me gusta, todo lo me hace falta y todo lo que he soñado.",
    "Cuando digo que busco un amor, no hablo de cualquier amor, sino del tuyo..!!",
    "En otras partes del mundo se están quejando, porque el sol está acá nada mas",
    "Si te duelen los pies es porque todo el día estuviste caminando en mi mente.",
    "No eres de color azul, ni negro, ni estas tan lejos, pero si eres mi cielo…",
    "De tu boca quiero un beso, de tu camisa un botón y de tu pecho… ¡EL CORAZÓN!",
    "Debes estar cansada, puesto que has estado corriendo en mi mente todo el día!",
    "Las 24 horas del día las divido así: 12 soñando contigo, y 12 pensando en ti.",
    "Mis ojos se sienten dignos, honorados y perplejos al ver tu apacible belleza.",
    "Oye, mi amor, sabes que eres el inquilino que no paga alquiler en mi corazón.",
    "Tantos años de ser jardinero y nunca había visto una flor más hermosa que tú.",
    "Quien quisiera ser tu Sol para alumbrar tu día y la luna para velar tus sueños.",
    "Tu madre debía de ser pastelera porque un bombón como tú no lo hace cualquiera.",
    "¡Oye nena! ¿Crees en el amor a primera vista, o voy a tener que pasar dos veces?",
    "Si Cristóbal Colón te viese, diría: Santa María, pero que Pinta tiene esta Niña.",
    "Si fuera piloto te llevaría en avión, pero como no lo soy te llevo en mi corazón",
    "Tu madre debe ser repostera, porque un bombón como vos no le sale a cualquiera.",
    "Tu madre debía de ser pastelera porque un bombón como tú no lo hace cualquiera.",
    "Aprovecha hoy que estoy en el mercado, los guapos como yo duramos dos días libres",
    "Aunque tenga todo el dinero del mundo, si no tengo tu amor me declaro en quiebra.",
    "Deja de respirar por un minuto, y sentirás lo que yo siento, cuando tú no estás.",
    "No te prometo un castillo, ni tampoco dinero, sólo mi corazón y mi cariño sincero",
    "Si Cristóbal Colón te viese, diría : Santa María, pero que Pinta tiene esta Niña",
    "Si pudieras ganar dinero con los me gustas que te tengo, te volvieras millonaria.",
    "Tal vez para el mundo sólo seas una persona, pero para una persona eres el mundo.",
    "Eres de esa clase de personas, por las cuales a las estrellas se les piden deseos.",
    "Fumo porque en el humo creo verte, y por miedo a perderte fumaré hasta la muerte.",
    "Si no supiera que los ángeles están en el cielo, juraría que tu eres uno de ellos.",
    "Te dejaré de amar a partir del día que encuentre el alfiler que ahora tiro al mar.",
    "¿Cómo quiere la gente que yo sea feliz si la mujer que yo quiero está lejos de mi?.",
    "Cómo no actuar como un imbécil, cuando tus ojos lo único que hacen es hipnotizarme.",
    "Quédate cerca de mí, al alcance de mi vista, te necesito más de lo que te imaginas.",
    "Si yo fuera Colón navegaría día y noche para llegar a lo más profundo de tu corazón",
    "Tal vez para el mundo sólo seas una persona, pero para esta persona eres el mundo.",
    "Azul es el cielo, verdes son las plantas, cafés son los ojos de la chica que me mata",
    "Puedes quedarte con mi corazón pero a cambio te pido que me llenes la vida de besos.",
    "Si fuera tu novio me volvería ateo, porque ya no tendría nada que pedirle a Diosito.",
    "Cuando te vi llegar le dije a mi corazón, que linda piedrecita para darme un tropezón",
    "Guapo no soy, riquezas no tengo pero te ofrezco mi corazón que es lo mejor que tengo!",
    "Mándale saludos a tus padres, porque me gusta la gente que sabe hacer las cosas bien.",
    "Si tus ojos fueran cárcel y yo carcelero, como me gustaría también ser el prisionero.",
    "Si un día pudiera volver a nacer, pediría ser la luna para poderte ver cada amanecer.",
    "Tantos años caminar por los jardines y nunca había visto una flor más hermosa que tú.",
    "Tu sensual mirada me hipnotiza mientras tus palabras envenenan a mi corazón con amor.",
    "Una noche muy bonita en tus ojos me miré, fue tan linda tu mirada que de ti me enamoré.",
    "Creo que fuiste mi amor en otra vida, porque nada más verte mi corazón comienza a latir.",
    "Disculpa si me comporto como un imbécil, pero es que tus ojos hipnotizan y vuelven loco.",
    "Napoleón con su espada conquistó varias naciones, tú con esos ojos conquistas corazones.",
    "Qué rico ser fosforito yo y que tú fueras vela para verte derretir cuando te de candela.",
    "Si en realidad el propósito de la vida es el amor, pues el propósito de la mía eres tu.",
    "Si en realidad el propósito de la vida es el amor, pues el propósito de la mía eres tú.",
    "Unos quieren el mundo, otros quieren el sol, pero yo solo quiero un rincón en tu corazón",
    "Cinco calles he cruzado, seis con el callejón, sólo me falta una para llegar a tu corazón",
    "El mayor obstáculo para el amor, es el temor secreto de no ser digno de ser amado por ti.",
    "Mírame a los ojos y verás la verdad: mi amor no es de un día sino para toda la eternidad.",
    "Napoleón con su espada conquisto una nación y vos con tu mirada conquistaste mi corazón.",
    "Qué triste es el mundo sin un ser amado, pero más triste es tenerlo y no estar a su lado.",
    "A veces me pregunto por qué la vida es tan bella. Ahora ya lo sé: Porqué tu estás en ella.",
    "Qué triste es el mundo sin un ser amado, pero más triste es tenerlo y no estar a su lado.",
    "Sólo tengo un propósito para este Año Nuevo, que tu vida y la mía escojan el mismo destino",
    "A las manzanas maderas se le come la masita, pero a una chica como tú se le come la boquita",
    "A veces me pregunto por qué la vida es tan bella. Ahora ya lo sé: Porqué tú estas en ella.",
    "Me gustaría ser una gota de tu sangre, para recoger todo tu cuerpo y dormir en tu corazón.",
    "Si tu cuerpo fuera la cárcel y tus brazos cadenas que bonito sitio para cumplir mi condena",
    "Busquen a las autoridades!!! Por? Una mujer tan bella debe estar protegida 24 horas al día.",
    "Como una reina te tendría todo el día entre algodón para que nunca se dañara tu gran corazón",
    "Eres eso a lo que todos le llaman mujer, a lo que yo simplemente le llamo: bendición divina.",
    "Es verdad que se necesita el corazón para vivir pero más te necesito a ti que lo haces latir",
    "Morir ya no me asusta, he visto el cielo en ti. No lo hago, simplemente me limito a amarte.",
    "Por un beso de tu boca y una noche en tus brazos daría todo el oro y el dinero que no tengo.",
    "¡Bendito sea el árbol de dónde sacaron la madera para hacer la cuna sobre la que te mecieron!",
    "Caminando por la calle, caminando te encontré, y al verte tan seria y guapa, de ti me enamoré",
    "Cuando te conocí me di cuenta que EL AMOR EXISTE, porque ahora no me imagino mi mundo sin ti.",
    "De todas las flores, la más bonita es la rosa y de todas las mujeres, tú eres la más hermosa",
    "Del cielo bajo un pintor para pintar tu figura, pero no encontró color para tanta hermosura.",
    "Es verdad que se necesita el corazón para vivir pero más te necesito a ti que lo haces latir.",
    "-Que hora cenes? -18:00 -Ah, por que quería saber el momento exacto en el que me volví loco.",
    "Si hay ángeles en el mundo y realmente nos observan, sin duda lo hacen a través de tus ojos.",
    "Contigo he tenido la historia de amor más bonita del mundo y tú ni siquiera te has enterado…",
    "Primero eres un amigo, después una ilusión y ahora eres lo más grande que llevo en el corazón.",
    "Quisiera ser pensamiento y estar dentro de ti y así saber el momento en que te acuerdas de mí.",
    "Si mi alma fuera pluma y mi corazón tintero, con la sangre de mis venas escribiría te quiero.",
    "Con cada vez que te veo, nueva admiración me das, y cuando te miro más, aun más mirarte deseo.",
    "El día en que te conocí, como que tembló en el cielo y cayo a la tierra un ángel que eras vos.",
    "El día que no te vea, para mí no sale el sol, y si sale no me alumbra como me alumbra tu amor.",
    "Es lindo ver el mar, subiéndose a las rocas, pero es más lindo alcanzar, con un besito, tu boca",
    "Me gustaría ser lágrimas para nacer en tus ojos, posarme en tus mejillas y morir en tus labios.",
    "Muchos te dirán, negrita por tí yo me muero, y yo que no te digo nada, soy el que más te quiero",
    "No serás la chica más bonita del mundo, pero si eres la chica que más bonito ha hecho mi mundo.",
    "Para mirar las estrellas no miro hacia arriba… mejor observo tus ojos, ya que tu eres mi cielo.",
    "Quisiera ser Cristóbal Colón para navegar noche y día y llegar a lo más profundo de tu corazón.",
    "Si yo fuera astronauta te llevaría a Plutón, pero como no lo soy te llevo siempre en mi corazón",
    "Del cielo cayo un pañuelo bordado de seda negra, y en cada esquina decía TU MADRE SERA MI SUEGRA",
    "Los pájaros piden comida, los presos su libertad. Yo te pido Amor mío que nunca me dejes de AMAR",
    "No hay necesidad de ser pintor, para dibujar una sonrisa en mi rostro triste. Basta con mirarte.",
    "Por suerte para mi, Dios no se dio cuenta del ángel que se le escapó para cruzarse en mi camino.",
    "Tú con tus ojos me miraste, yo de piedra me quedé; y en ese mismo instante, yo de ti m enamoré.",
    "Cuando estoy contigo siento que lo imposible se hace posible, cundo te vas todo se hace difícil.",
    "El día que tú nacisteis, el sol se puso celoso… pues había un nuevo solcito mucho más luminoso.",
    "Esta noche he soñado que al despertar esta mañana te estaría abrazando a ti en vez de mi almohada",
    "Mi vida no la cuento por las veces que respiro, si no por las veces que me quitas la respiración.",
    "Por la luna doy un beso, por el sol doy un montón, por la luz de tu mirada, alma, vida y corazón.",
    "Qué bonito es el amor, qué bonito es el cielo… pero más bonito sería que tú me digas “te quiero”.",
    "Si tienes que caminar 100 pasos para llegar a mí, solo camina uno, que yo caminaré los 99 por ti.",
    "Las estrellas están enojadas con Dios, porque no las hicieron tan hermosas como te hicieron a vos.",
    "Mira como cae el agua cuando deja de llover … así caerán mis lagrimas cuando me dejes de querer.",
    "Quisiera ser mar y que tú fueras la roca, para que cuando suba la marea, poder besarte en la boca.",
    "Sabes por que hay un agujero en la capa de ozono?? -Por que? -Por que tus ojos miraron al cielo!!",
    "Anoche tuve un sueño, que me llenó de emoción. Soñé que te daba un beso, y tú, a cambio, el corazón",
    "No me mires, no me hables… sólo quiero saber con la dulzura de un beso si me has empezado a querer.",
    "Ramitos de alfileres parecen tus pestañas, que cada vez que las miro se me clavan en mis entrañas.",
    "Mi amor por ti, vida mía, es tan grande y tan inmenso, que por caber no cabría en todo el universo.",
    "Mira cómo caen los cocos al moverse las palmeras, así se me van los ojos cuando mueves las caderas.",
    "Labios de fresa, ojos de chocolate y piel de miel,con esos ingredientes tu madre hizo el mejor pastel",
    "Cuando busque un destino del que no quiera escapar, te buscaré a ti porque tú eres mi único destino…",
    "De tu boca quiero un beso, de tu camisa un botón, de tu pensamiento un deseo y de tu pecho el corazón.",
    "Desearía ser una lágrima tuya… para nacer en tus ojos, Navegar por tus mejillas, y morir en tus labios",
    "Antes de volverte a mirar necesito comprarme un seguro de vida, no vaya a ser que me mate tu sonrisa…",
    "Ayer pasé por tu casa y me tiraste un ladrillo … mañana pasaré de nuevo para construirte un castillo.",
    "Al pasar por un jardín las flores entristecieron, porque al verte pasar, a la flor más bella conocieron.",
    "Cómo quieres que te olvide si cuando empiezo a olvidarte recuerdo que te olvido y empiezo a recordarte.",
    "Los zapatitos me aprietan, las medias me dan calor, y el muchachito de enfrente, me tiene loca de amor.",
    "Me gustaría ser cigarro mentolado para que me consumas con tus labios y mi humo este siempre a tu lado.",
    "Si todo lo que te quiero se pudiera representar, no me alcanzaría el cielo y el mar para poderlo pintar.",
    "Si verte fuera la muerte, y no verte fuera la vida, prefiero la muerte y verte, a no verte y tener vida.",
    "Tú deberías estar cansada ? Ella dice: ¿Por qué? Porque has estado corriendo en mi mente todo el día.",
    "Es tan lindo saber que tú existes y que me tocó vivir en este tiempo y este espacio para poder conocerte.",
    "Por ti cariño, soy capaz de bajarte las estrellas para observar.. si son tan brillantes como tu sonrisa.",
    "Desearía ser una lágrima tuya… Para nacer en tus ojos, Navegar por tus mejillas, Y morir en tus labios.",
    "Le dices a la dama en su bello caminar: ¡Como avanza la tecnología….! ….QUE HASTA LAS FLORES CAMINAN.",
    "Que pobre es el labrador que no puede labrar el trigo pero más pobre soy yo cuando no pueda estar contigo.",
    "Si la estrella de Oriente guía a los marineros, yo me guío con tus ojos que me alumbran más que mil luceros.",
    "La sonrisa de tus labios quita brillo al mundo entero, pero ¿qué me importa el mundo, si yo tengo mi lucero?.",
    "Las estrellas están enojadas con Dios Por qué ? -Porqué no las hicieron tan bonitas como te hicieron a vos",
    "Si cada vez que pensara en ti una estrella se apagara, no habría en el firmamento una estrella que brillara.",
    "El amor no es como lo pintan, ni como lo cantan, ni como lo escriben. El amor es como lo que yo siento por ti.",
    "No existen puertas que el amor no abra, abismo que el amor no cruce, ni pecado que suficiente amor no redima.",
    "Tu madre es una ladrona, por que el día que naciste se robo dos estrellas del universo y las puso en tus ojos",
    "Pregunta a la infinidad del cielo cuánto te amo, y verás que ni Él lo sabe; te amo tanto, que ni Dios lo sabe.",
    "Quisiera tener un barco pirata, para navegar por el mar rojo de tus labios y así llegar al tesoro de tu corazón",
    "La soledad y la tristeza se sienten frustrados, pues a mi no me han podido atrapar, pues tus manos me aguardan.",
    "Si por cada vez que pienso: te quiero, me dieran dinero, sería la chico más rico del mundo entero.",
    "Si te ofendí al besarte, si te parece una ofensa grave el besarte, desquítate, anda y págame con la misma moneda.",
    "No permitas que las lagrimas empañen la belleza de tus ojos, porque no te permiten ver el bello amanecer del día.",
    "Bendita sea la yerba que se trago la borrega de donde sacaron la lana para hacerle la sotana al cura que te bautizó",
    "El sol sale por la ventana, y a tu ventana va a parar, fíjate si eres hermosa, que hasta el sol te viene a despertar",
    "Eres la LUZ de mi mundo. Cuando estás conmigo se llena mi corazón, tiene sentido la vida y el mundo es una ilusión.",
    "Tu madre es una ladrona, por que el día que naciste se robo todas las estrellas del universo y las puso en tus ojos",
    "El sol sale por la ventana, y a tu ventana va a parar, fíjate si eres hermosa, que hasta el sol te viene a despertar.",
    "Ni aunque el cielo fuera hecho de papel y los océanos de tinta, no habría lugar para escribir todo lo que te quiero.",
    "Por ti cariño, soy capaz de bajarte las estrellas para observar.. si son tan brillantes como tu sonrisa corazoncito.",
    "Una rosa es la mínima expresión de belleza de una mujer y una mujer es la máxima expresión de belleza de una rosa…",
    "Sé que no soy ni el más bonito ni el más deseado pero si sé que puedo pasar el resto de tu vida a tu lado porque te amo",
    "No miento si te digo que eres lo mejor que me ha pasado, lo mejor que me pasa y lo mejor que quiero que me siga pasando.",
    "Sé que no soy ni el más bonito ni el más deseado pero si sé que puedo pasar el resto de tu vida a tu lado porque te amo.",
    "Que ojos tan lindos tienes, debajo de esas dos cejas, y yo quisiera ser alguna estrella, para así vigilare de muy cerca.",
    "Si te hace falta algún te quiero, algún te adoro o algún loco que viva para ti, entonces piensa en mí… y cuenta conmigo.",
    "Afortunadas las margaritas que adornan tu diminuta blusa, cuanto desearía ser una para escuchar los latidos de tu corazón.",
    "Cuando te conocí tuve miedo de mirarte, cuando te miré tuve miedo de quererte, y ahora que te quiero tengo miedo de perderte.",
    "Quisiera ser el aire que respiras, quisiera ser el sol que te ilumina, pero lo que más quisiera ser, es el amor de tu vida!!!",
    "Me gustaría ser la sangre que recorre todo tu cuerpo para llegar a lo más profundo de tu corazón y conquistarlo para siempre.",
    "El agua busca la vertiente, la vertiente el río, y el río busca el mar, mientras yo busco tus hermosos labios para poderte besar.",
    "Quisiera ser el sol para alumbrar tus días, luna para velar tus sueños, lluvia para mojar tu cabello y viento para rozar tu piel.",
    "-¿Sabías que el amor es como las matemáticas? No ¿Por qué? Porque es mas amor, menos dolor, por toda la vida y dividido entre tú y yo.",
    "Si por cada momento que yo pienso en ti, yo ganara un segundo de vida, estoy seguro, que no iba a morir porque yo pienso en ti noche y día.",
    "Te quiero, así sin espacios, TE QUIERO en mayúsculas, tq en abreviatura, te Quiero hasta con faltas de ortografía, pero de verdad te quiero…",
    "Eres tú de esas mujeres maravillosas que conquistan sin faldas cortas, sin grandes escotes. Solo con una sonrisa, tu mirada y tu forma de ser.",
    "Cualquier persona puede hacerme feliz haciendo algo especial, pero solo alguien especial puede hacerme feliz sin hacer nada… como lo haces tú.",
    "El Amor es como una noche de estrellas pura y sincera rodeado de los encantos de la naturaleza, tú serás la estrella mas eterna para darte mí pureza",
    "Todo comenzó con una mirada y una sonrisa, después vino un me gustas, seguido de un te quiero, hasta llegar a un te amo y a un no puedo vivir sin ti…",
    "No me preguntes como llegue a quererte ni cuánto. Responderte yo no puedo. Si Dios me dio este amor para adorarte, que te conteste Dios cuanto te quiero.",
    "Yo soy tuyo y tú eres mía; de ellos puedes tener la certeza. Tú estás encerrada en mi corazón; la llave se ha perdido y deberás quedar dentro eternamente",
    "Yo soy tuyo y tú eres mía; de ellos puedes tener la certeza. Tú estás encerrada en mi corazón; la llave se ha perdido y deberás quedar dentro eternamente.",
    "Si tú fueras vigilante de playa, quisiera ser aquella persona que se está ahogando, para ver tu hermosa cara después de despertar, gracias a tu boca a boca.",
    "Si fuera cantante te dedicaría una canción, si fuera jugador te dedicaría un gol, pero como no soy ni cantante ni jugador, sólo tengo para dedicarte mi corazón.",
    "Antes que nada quiero felicitarte por ser este el día más especial de tu vida, y de la mía también, ya que un día como hoy nació el ser más maravilloso que haya podido conocer.",
    "Qué dicha la de mis ojos que pueden apreciar tu hermosura, más dichoso es el viento que acaricia tu figura, pero pobre mi corazón que lo tienes despreciado y camino a su sepultura.",
    "Qué dicha la de mis ojos que pueden apreciar tú hermosura, más dichoso es el viento que acaricia tu figura, pero pobre mi corazón que lo tienes despreciado y camino a su sepultura.",
    "Mujer eres poderosa… Con una sonrisa como la tuya, no necesitas ningún cosmético. Con una mirada como la tuya, no te hace falta una pistola ni un cañón. Y si hablas con ese encanto y dulzura, rindes a tus pies cualquier varón.",
]